### ISSUE TITLE
Dithering options not displayed in gimp 2.10.*

### ISSUE THREAD

**Issue by clort81** [cybernesto/VBMP#1]
Trying to get this working in gimp 2.10.

The python script is in my userscripts directory.  The .py is executeable.  But the dithering options are not showing-up when i convert to indexed and select dithering options.

Can you confirm the issue?  Thanks.

**Comment by clort81** [comment]
The documentation was misleading - the plugin is findable under the 'Colors' menu, not Image->Mode->Indexed.  Closing.

**Comment by cybernesto** [comment]
Wow, someone is using this! I’m flattered. The Wiki shows the standard dithering menu but the plugin read me actually mentions the Color menu. Glad that you found it anyway.
